# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0002_auto_20190325_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prof_image',
            new_name='picture',
        ),
    ]
