# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0003_auto_20190326_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='viva/'),
        ),
    ]
