# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsanimals', '0004_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pet_id',
            new_name='pet',
        ),
    ]
