# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsanimals', '0005_auto_20190417_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_details',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_price',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
